POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYxOTM5NTQyLCJ1c2VySWQiOjF9.DrXPQ3X1CKciG4BFNFgTdLbZNtaPAQScQ2SCB9Ywmls

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-31-10T15:30:00.000Z"
}

